obj-y = \
	m3_bind.o \
	m3_code.o \
	m3_compile.o \
	m3_core.o \
	m3_env.o \
	m3_exec.o \
	m3_function.o \
	m3_info.o \
	m3_module.o \
	m3_parse.o \
	module.o

COMMON_CFLAGS := -Wno-error=implicit-function-declaration -std=gnu11 -Wno-error=strict-prototypes -Wno-error=unused-variable \
	-Wno-error=declaration-after-statement
CFLAGS_m3_bind.o = $(COMMON_CFLAGS)
CFLAGS_m3_compile.o = $(COMMON_CFLAGS)
CFLAGS_m3_core.o = $(COMMON_CFLAGS)
CFLAGS_m3_env.o = $(COMMON_CFLAGS)
CFLAGS_m3_exec.o = $(COMMON_CFLAGS)
CFLAGS_m3_function.o = $(COMMON_CFLAGS)
CFLAGS_m3_info.o = $(COMMON_CFLAGS)
CFLAGS_m3_module.o = $(COMMON_CFLAGS)
CFLAGS_m3_parse.o = $(COMMON_CFLAGS)
